In [22]:
import sqlite3
import pandas as pd

df = pd.read_csv('../data/processed/telco_cleaned.csv')
conn = sqlite3.connect('../data/churn.db')
df.to_sql('customers', conn, if_exists='replace', index=False)
print("✅ Data loaded into SQLite — table: customers")

✅ Data loaded into SQLite — table: customers

In [27]:
with open('../sql/churn_analysis_queries.sql', 'r') as file:
    sql_content = file.read()

In [29]:
queries = sql_content.split(';')

In [4]:
query1 = queries[0]

df1 = pd.read_sql_query(query1, conn)
df1

   Total_Customers  Churned  Churn_Rate_Pct  Avg_Churned_Monthly_Bill
0             7043     1869           26.54                     74.44

In [5]:
df1.to_csv('../data/sql_outputs/q1_overall_churn_rate_summary.csv', index=False)

In [6]:
query2 = queries[1]

df2 = pd.read_sql_query(query2, conn)
df2

         Contract  Total  Churned  Churn_Rate_Pct
0  Month-to-month   3875     1655           42.71
1        One year   1473      166           11.27
2        Two year   1695       48            2.83

In [7]:
df2.to_csv('../data/sql_outputs/q2_churn_rate_by_contract_type.csv', index=False)

In [8]:
query3 = queries[2]

df3 = pd.read_sql_query(query3, conn)
df3

        Tenure_Cohort  Customers  Churn_Pct  Avg_Monthly_Charge
0   0-12 months (New)       2186      47.44               56.10
1        13-24 months       1024      28.71               61.36
2        25-48 months       1594      20.39               65.93
3  49+ months (Loyal)       2239       9.51               73.95

In [9]:
df3.to_csv('../data/sql_outputs/q3_churn_bytenure_bucket.csv', index=False)

In [10]:
query4 = queries[3]

df4 = pd.read_sql_query(query4, conn)
df4

  InternetService  Customers  Churn_Rate  Avg_Bill
0             DSL       2421       18.96     58.10
1     Fiber optic       3096       41.89     91.50
2              No       1526        7.40     21.08

In [11]:
df4.to_csv('../data/sql_outputs/q4_churn_by_internet_service_type.csv', index=False)

In [12]:
query5 = queries[4]

df5 = pd.read_sql_query(query5, conn)
df5

   Segment_Size  Churn_Rate  Revenue_At_Risk
0          1307       60.37          68281.5

In [13]:
df5.to_csv('../data/sql_outputs/q5_high_risk_segment.csv', index=False)

In [14]:
query6 = queries[5]

df6 = pd.read_sql_query(query6, conn)
df6

  SeniorCitizen  Customers  Churn_Rate
0            No       5901       23.61
1           Yes       1142       41.68

In [15]:
df6.to_csv('../data/sql_outputs/q6_churn_rate_by_senior_citizen_status.csv', index=False)

In [16]:
query7 = queries[6]

df7 = pd.read_sql_query(query7, conn)
df7

   Monthly_Revenue_Lost  Lifetime_Revenue_Lost
0             139130.85              2862926.9

In [17]:
df7.to_csv('../data/sql_outputs/q7_monthly_revenue_lost_to_churn.csv', index=False)

In [18]:
query8 = queries[7]

df8 = pd.read_sql_query(query8, conn)
df8

  TechSupport  Churn_Rate
0          No       41.64
1         Yes       15.17

In [19]:
df8.to_csv('../data/sql_outputs/q8_impact_of_tech_support_on_churn.csv', index=False)

In [30]:
query9 = queries[8]

df9 = pd.read_sql_query(query9, conn)
df9

    tenure        Contract  MonthlyCharges InternetService Risk_Level
0       72        Two year          118.75     Fiber optic   LOW RISK
1       71        Two year          118.65     Fiber optic   LOW RISK
2       68        Two year          118.60     Fiber optic   LOW RISK
3       61        One year          118.60     Fiber optic   LOW RISK
4       72        Two year          118.20     Fiber optic   LOW RISK
5       72        Two year          117.60     Fiber optic   LOW RISK
6       72        Two year          117.50     Fiber optic   LOW RISK
7       72        Two year          117.35     Fiber optic   LOW RISK
8       68        One year          117.20     Fiber optic   LOW RISK
9       72        Two year          117.15     Fiber optic   LOW RISK
10      72        Two year          116.95     Fiber optic   LOW RISK
11      72        Two year          116.85     Fiber optic   LOW RISK
12      72        Two year          116.80     Fiber optic   LOW RISK
13      72        Two year          116.75     Fiber optic   LOW RISK
14      60        One year          116.60     Fiber optic   LOW RISK
15      72        Two year          116.60     Fiber optic   LOW RISK
16      70        Two year          116.55     Fiber optic   LOW RISK
17      55  Month-to-month          116.50     Fiber optic   LOW RISK
18      72        Two year          116.45     Fiber optic   LOW RISK
19      72        Two year          116.40     Fiber optic   LOW RISK
20      71        One year          116.30     Fiber optic   LOW RISK
21      34        One year          116.25     Fiber optic   LOW RISK
22      71        Two year          116.25     Fiber optic   LOW RISK
23      66        One year          116.25     Fiber optic   LOW RISK
24      34        Two year          116.15     Fiber optic   LOW RISK
25      71        Two year          116.10     Fiber optic   LOW RISK
26      67        Two year          116.10     Fiber optic   LOW RISK
27      72        Two year          116.05     Fiber optic   LOW RISK
28      71        Two year          116.05     Fiber optic   LOW RISK
29      60        Two year          116.05     Fiber optic   LOW RISK
30      69        Two year          116.00     Fiber optic   LOW RISK
31      56        Two year          115.85     Fiber optic   LOW RISK
32      72        Two year          115.80     Fiber optic   LOW RISK
33      72        Two year          115.80     Fiber optic   LOW RISK
34      72        Two year          115.80     Fiber optic   LOW RISK
35      66        One year          115.80     Fiber optic   LOW RISK
36      72        Two year          115.75     Fiber optic   LOW RISK
37      72        Two year          115.75     Fiber optic   LOW RISK
38      45  Month-to-month          115.65     Fiber optic   LOW RISK
39      72        Two year          115.60     Fiber optic   LOW RISK
40      54        One year          115.60     Fiber optic   LOW RISK
41      62        Two year          115.55     Fiber optic   LOW RISK
42      72        Two year          115.55     Fiber optic   LOW RISK
43      72        Two year          115.55     Fiber optic   LOW RISK
44      72        Two year          115.50     Fiber optic   LOW RISK
45      72        Two year          115.50     Fiber optic   LOW RISK
46      60        Two year          115.25     Fiber optic   LOW RISK
47      71        Two year          115.15     Fiber optic   LOW RISK
48      72        Two year          115.15     Fiber optic   LOW RISK
49      70        Two year          115.15     Fiber optic   LOW RISK

In [32]:
df9.to_csv('../data/sql_outputs/q9_top50_churn_risk_customers.csv', index=False)

In [33]:
query10 = queries[9]

df10 = pd.read_sql_query(query10, conn)
df10

   Services_Count  Customers  Churn_Rate
0               1       1804       13.08
1               2       2511       46.36
2               3       1797       21.15
3               4        931        9.56

In [34]:
df10.to_csv('../data/sql_outputs/q10_churn_rate_by_number_of_services.csv', index=False)